# Task 1:

In [2]:
#Write a function to compute 5/0 and use try/except to catch the exceptions. 

In [11]:
def compute():
    den=int(input('enter the denominator:'))
    try:
        a=5/den
        print(a)
    except:
        print('invalid denominator')

In [14]:
compute()

enter the denominator:0
invalid denominator


In [15]:
compute()

enter the denominator:2
2.5


In [16]:
#Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

In [31]:
subjects=["Americans ","Indians"] 
verbs=["play","watch"] 
objects=["Baseball","Cricket"]
a=[print(i,j,k) for i in subjects for j in verbs for k in objects]

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


# Task 2:

In [34]:
#Write a function so that the columns of the output matrix are powers of the input vector.  
#The order of the powers is determined by the increasing boolean argument. Specifically, 
#when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1. 

In [94]:
import numpy as np
def my_ATV_version():
    input_matrix=list(map(int,input('enter the matrix:')))   
    data=np.array(input_matrix)
    print(data)
    N=int(input('enter the multiplier:'))
    data1=np.column_stack([data**(N-1-i) for i in range(N)])
    print(data1)      

In [95]:
my_ATV_version()

enter the matrix:1234
[1 2 3 4]
enter the multiplier:4
[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]
